---
- name: Set up 3-node Vault cluster with Raft
  hosts: all
  vars_files:
    - vars/main.yml
  tasks:
    - include_tasks: tasks/0_destroy.yml
    - include_tasks: tasks/1_create_and_start.yml
    - include_tasks: tasks/2_initialize.yml
    # - include_tasks: tasks/3_unseal.yml
