---
- name: Check if vault root folder exists
  ansible.builtin.stat:
    path: "{{ vault_dir }}"
  register: vault_root_dir_stat

- name: Clean up before we go
  when: vault_root_dir_stat.stat.exists and vault_root_dir_stat.stat.isdir and (destroy is defined and destroy | bool)
  block:
    - name: Stop vault cluster
      ansible.builtin.command:
        cmd: /usr/local/bin/podman-compose down
        chdir: "{{ vault_dir }}"
      register: compose_result
      changed_when: compose_result.rc == 0
      environment:
        DOCKER_HOST: "unix:///run/user/{{ ansible_user_id }}/podman/podman.sock"

    - name: Clean up before we go
      become: true
      file:
        path: "{{ vault_dir }}"
        state: absent
