---
- name: Create Vault project directory structure
  become: true
  file:
    path: "{{ vault_dir }}/{{ item }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0777'
  loop:
    - config
    - data
  
- name: Create Vault configuration files
  become: true
  vars:
      node_name: "{{ inventory_hostname }}"
  template:
    src: templates/vault_config.hcl.j2
    dest: "{{ vault_dir }}/config/vault.hcl"
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Create docker-compose.yaml
  vars:
      node_name: "{{ inventory_hostname }}"
  template:
    src: templates/docker_compose.yaml.j2
    dest: "{{ vault_dir }}/docker-compose.yaml"
    mode: '0644'

- name: Ensure podman-compose is up
  ansible.builtin.command:
    cmd: /usr/local/bin/podman-compose up -d
    chdir: "{{ vault_dir }}"
  register: compose_result
  changed_when: compose_result.rc == 0
  environment:
    DOCKER_HOST: "unix:///run/user/{{ ansible_user_id }}/podman/podman.sock"
