---
- name: Check Leader State
  uri:
    url: http://localhost:8200/v1/sys/health
    status_code: [200, 501, 503]
    return_content: true
  register: leader_health
  when: "inventory_hostname == leader_node"

- name: Initialize Leader if necessary
  when: "inventory_hostname == leader_node and leader_health.status in [501]"
  block:
    - name: Initialize Leader
      command: "podman exec vault-node vault operator init -key-shares={{ unseal_keys_shares }} -key-threshold={{ unseal_keys_threshold }} -format=json"
      register: vault_init
      environment:
        VAULT_ADDR: "http://{{ leader_node }}:8200"
      changed_when: true
      
    - name: Parse initialization output
      set_fact:
        vault_init_json: "{{ vault_init.stdout | from_json }}"
        cacheable: yes

    - name: dump init output
      debug:
        msg: "{{ vault_init_json }}"

    - name: Save unseal keys and root token
      copy:
        content: "{{ vault_init_json }}"
        dest: "{{ vault_init_file }}"
        mode: '0600'
