---
- name: Is the Cluster Initialized?
  when: "inventory_hostname == first_node"
  block:
    - name: Check if Vault is initialized
      ansible.builtin.uri:
        url: "http://{{ first_node }}:8200/v1/sys/init"
        method: GET
        return_content: true
        status_code: 200
        validate_certs: false
      register: vault_init_status

    - name: Set fact for Vault initialization status
      set_fact:
        vault_initialized: "{{ vault_init_status.json.initialized | default(false)}}"

    - name: Announce Vault initialization status
      debug:
        msg: "Cluster is initialized: {{ vault_initialized }}"

- name: Initialize Cluster
  when: "inventory_hostname == first_node and not vault_initialized"
  block:
    - name: Initialize Leader
      command: "podman exec vault-node vault operator init -key-shares={{ unseal_keys_shares }} -key-threshold={{ unseal_keys_threshold }} -format=json"
      register: vault_init
      environment:
        VAULT_ADDR: "http://{{ first_node }}:8200"
      changed_when: true
      
    - name: Parse initialization output
      set_fact:
        vault_init_json: "{{ vault_init.stdout | from_json }}"
        cacheable: yes

    - name: dump init output
      debug:
        msg: "{{ vault_init_json }}"

    - name: Save unseal keys and root token
      copy:
        content: "{{ vault_init_json }}"
        dest: "{{ vault_init_file }}"
        mode: '0600'
