---
- name: Unseal+Join Secondary Nodes
  when: hostvars[inventory_hostname].vault_sealed
  block:
    - name: Join Cluster (this is idempotent)
      when: inventory_hostname != first_node # first node does not join itself
      command: podman exec vault-node vault operator raft join http://{{ first_node }}:8200
      environment:
        VAULT_ADDR: "http://{{ inventory_hostname }}:8200"

    - name: Unseal Node
      command: podman exec vault-node vault operator unseal {{ item }}
      loop:
        - "{{ hostvars[first_node].unseal_keys_b64[0] }}"
        - "{{ hostvars[first_node].unseal_keys_b64[1] }}"
        - "{{ hostvars[first_node].unseal_keys_b64[2] }}"
      environment:
        VAULT_ADDR: "http://{{ inventory_hostname }}:8200"
